### ISSUE TITLE
satromo_publish.py crashes if Google Drive API is not enabled

### ISSUE THREAD

**Issue by metaodi** [swisstopo/topo-satromo#100]
**Describe the bug**

At the end of `satromo_publish.py` there is an attempt to delete files on GDrive, this should only be executed if `config.GDRIVE_TYPE == "DRIVE"`

https://github.com/swisstopo/topo-satromo/blob/a272e9284f4cb56399117b83f560212b655f4a63/satromo_publish.py#L994-L999

 Since we do not have Google Drive enabled, the `drive.ListFile` call fails and crashes the script (even though the actual publish process was successful).

**To Reproduce**

1. Run the `satromo_publish.py` script with a config file that defines GDRIVE_TYPE = "GCS"
2. Use an account, where Google Drive is not enabled.

See error message:

```
Traceback (most recent call last):
  File "D:\data\224392_satromo\topo-satromo\satromo_publish.py", line 995, in <module>
    file_list = drive.ListFile({'q': "trashed=true"}).GetList()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\data\224392_satromo\topo-satromo\pyenv\Lib\site-packages\pydrive\apiattr.py", line 162, in GetList
    for x in self:
  File "D:\data\224392_satromo\topo-satromo\pyenv\Lib\site-packages\pydrive\apiattr.py", line 146, in __next__
    result = self._GetList()
             ^^^^^^^^^^^^^^^
  File "D:\data\224392_satromo\topo-satromo\pyenv\Lib\site-packages\pydrive\auth.py", line 75, in _decorated
    return decoratee(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\data\224392_satromo\topo-satromo\pyenv\Lib\site-packages\pydrive\files.py", line 63, in _GetList
    self.metadata = self.auth.service.files().list(**dict(self)).execute(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\data\224392_satromo\topo-satromo\pyenv\Lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\data\224392_satromo\topo-satromo\pyenv\Lib\site-packages\googleapiclient\http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting
https://www.googleapis.com/drive/v2/files?q=trashed%3Dtrue&maxResults=1000&alt=json
returned "Google Drive API has not been used in project 722976925574 before or it is disabled. Enable it by visiting
https://console.developers.google.com/apis/api/drive.googleapis.com/overview?project=722976925574
then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.". Details: "[{'message': 'Google Drive API has not been used in project 722976925574 before or it is disabled. Enable it by visiting
https://console.developers.google.com/apis/api/drive.googleapis.com/overview?project=722976925574
then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.', 'domain': 'usageLimits', 'reason': 'accessNotConfigured', 'extendedHelp': '
https://console.developers.google.com'}]">
```

**Expected behavior**

Do not attempt to call Google Drive APIs if GCS is configured.

**Comment by davidoesch** [comment]
nice catch
 *should* be fixed with now on PROD as well, just get the lates version of 

https://github.com/swisstopo/topo-satromo/blob/main/satromo_publish.py
